name: polymer_expressions
version: 0.13.0+2
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: An expressive custom binding syntax for HTML templates
homepage: http://www.dartlang.org/polymer-dart/
dependencies:
  browser: ">=0.10.0"
  observe: ">=0.11.0"
  template_binding:
    git: https://github.com/blckur/template-binding.git
dev_dependencies:
  unittest: ">=0.10.0"
  benchmark_harness: ">=1.0.0"
environment:
  sdk: ">=1.2.0"
